# VirtualPeripheral — a BLE Heart Rate peripheral whose whole GATT-server behaviour
# is driven from Ruby. `class VirtualPeripheral < BLE` (role :peripheral); the
# picoruby-ble Darwin port turns these Ruby calls into CoreBluetooth operations.
# Ruby owns: when to advertise, what each read returns, how writes are handled,
# when to notify. CoreBluetooth (the Apple framework) is driven through the port —
# this app contains no Swift and no CoreBluetooth code.
#
# The reduced iOS VM lacks Array#pack / String#<< / Integer#chr, so the ATT-DB
# profile_data and the AD-TLV adv_data are generated OFFLINE by tools/gen_profile.rb
# (which runs the real BLE::GattDatabase / BLE::AdvertisingData under CRuby) and
# embedded below as frozen literals — byte-identical to what rp2040 compiles.
# Everything below the literals is live behaviour, written for the reduced VM
# (getbyte / +/ [i,1] / a 256-byte lookup for int->byte; no pack/<</chr/sprintf).

# === GENERATED by tools/gen_profile.rb — do not edit by hand ===
# Heart Rate service 0x180D: 0x2A37 (READ|NOTIFY + CCCD), 0x2A39 (WRITE).
# att value handles: 0x2A37 => 3, CCCD 0x2902 => 4, 0x2A39 => 6.
PROFILE_DATA = "\x01\x0a\x00\x02\x00\x01\x00\x00\x28\x0d\x18\x0d\x00\x02\x00\x02\x00\x03\x28\x12\x03\x00\x37\x2a\x0a\x00\x02\x01\x03\x00\x37\x2a\x00\x00\x0a\x00\x0a\x01\x04\x00\x02\x29\x00\x00\x0d\x00\x02\x00\x05\x00\x03\x28\x08\x06\x00\x39\x2a\x09\x00\x08\x01\x06\x00\x39\x2a\x00\x00\x00".freeze
ADV_DATA = "\x02\x01\x06\x03\x03\x0d\x18\x0a\x09\x50\x42\x4c\x45\x2d\x54\x45\x53\x54".freeze
BYTE_TABLE = "\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f\x20\x21\x22\x23\x24\x25\x26\x27\x28\x29\x2a\x2b\x2c\x2d\x2e\x2f\x30\x31\x32\x33\x34\x35\x36\x37\x38\x39\x3a\x3b\x3c\x3d\x3e\x3f\x40\x41\x42\x43\x44\x45\x46\x47\x48\x49\x4a\x4b\x4c\x4d\x4e\x4f\x50\x51\x52\x53\x54\x55\x56\x57\x58\x59\x5a\x5b\x5c\x5d\x5e\x5f\x60\x61\x62\x63\x64\x65\x66\x67\x68\x69\x6a\x6b\x6c\x6d\x6e\x6f\x70\x71\x72\x73\x74\x75\x76\x77\x78\x79\x7a\x7b\x7c\x7d\x7e\x7f\x80\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b\x8c\x8d\x8e\x8f\x90\x91\x92\x93\x94\x95\x96\x97\x98\x99\x9a\x9b\x9c\x9d\x9e\x9f\xa0\xa1\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xab\xac\xad\xae\xaf\xb0\xb1\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xbb\xbc\xbd\xbe\xbf\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\xd0\xd1\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xdb\xdc\xdd\xde\xdf\xe0\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef\xf0\xf1\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff".freeze
# === end generated ===

HR_MEAS_HANDLE = 3   # 0x2A37 Heart Rate Measurement (READ | NOTIFY)
CCCD_HANDLE    = 4   # 0x2902 Client Characteristic Configuration of 0x2A37
CONTROL_HANDLE = 6   # 0x2A39 Heart Rate Control Point (WRITE)

class VirtualPeripheral < BLE
  def initialize
    super(:peripheral, PROFILE_DATA)
    @log = []
    @subscribed = false
    @awaiting_send = false
    @bpm = 60
    # Seed the read cache so a read before any subscription returns a value.
    push_read_value(HR_MEAS_HANDLE, hr_measurement(@bpm))
    hci_power_control(HCI_POWER_ON)
    log "booted: powering on radio, profile #{PROFILE_DATA.length}B"
  end

  # One poll iteration. The Swift timer calls this ~10x/sec. pop_packet drains one
  # CoreBluetooth event (and, on Darwin, reconciles the read cache / write queue on
  # this VM thread). Returns nothing; prints accumulated log lines as captured stdout.
  def tick(arg = nil)
    pkt = pop_packet
    packet_callback(pkt) if pkt
    poll_cccd
    poll_control_point
    # Drive a steady notification stream while a central is subscribed: ask the
    # stack when it can send, and emit the next measurement on CAN_SEND_NOW (0xB7).
    if @subscribed && !@awaiting_send
      request_can_send_now_event
      @awaiting_send = true
    end
    flush_log
  end

  # The four peripheral-role events the Darwin port forwards (see ports/darwin/README).
  def packet_callback(event)
    case event.getbyte(0)
    when 0x60   # BTSTACK_EVENT_STATE: services added, radio working
      advertise(ADV_DATA)
      log "radio working -> advertising as PBLE-TEST"
    when 0x05   # disconnection
      @subscribed = false
      @awaiting_send = false
      log "central disconnected"
    when 0xB5   # MTU exchange complete: first subscription from a central
      log "mtu exchanged (central present)"
    when 0xB7   # CAN_SEND_NOW: the moment to push one notification
      @bpm += 1
      @bpm = 60 if @bpm > 180
      push_read_value(HR_MEAS_HANDLE, hr_measurement(@bpm))
      notify(HR_MEAS_HANDLE)
      @awaiting_send = false
      log "notified hr=#{@bpm}"
    end
  end

  private

  # CCCD write toggles subscription. Canonical path: pop_write_value(cccd) returns
  # "\x01\x00" (subscribe) or "\x00\x00" (unsubscribe).
  def poll_cccd
    v = pop_write_value(CCCD_HANDLE)
    return unless v
    if v.getbyte(0) == 0x01
      @subscribed = true
      @awaiting_send = false
      log "subscribed -> streaming heart rate"
    else
      @subscribed = false
      log "unsubscribed"
    end
  end

  # A write to the Heart Rate Control Point (0x2A39). 0x01 = "reset energy expended";
  # here we just log it and reset the simulated rate, proving Ruby sees the bytes.
  def poll_control_point
    v = pop_write_value(CONTROL_HANDLE)
    return unless v
    log "control point write: #{hex(v)}"
    if v.length > 0 && v.getbyte(0) == 0x01
      @bpm = 60
      log "  -> reset heart rate to 60"
    end
  end

  # Heart Rate Measurement value: flags byte 0x00 (UINT8 BPM, no extras) + the rate.
  def hr_measurement(bpm)
    byte(0x00) + byte(bpm)
  end

  # Integer (0..255) -> 1-byte String, without chr/pack (absent in the reduced VM).
  def byte(n)
    BYTE_TABLE[n & 0xff, 1]
  end

  # Hex-encode a binary string for logging (no sprintf in the reduced VM).
  def hex(s)
    digits = "0123456789abcdef"
    out = ""
    i = 0
    while i < s.length
      b = s.getbyte(i)
      out += digits[(b >> 4) & 0x0f, 1]
      out += digits[b & 0x0f, 1]
      i += 1
    end
    out
  end

  def log(msg)
    @log.push(msg)
  end

  def flush_log
    return nil if @log.empty?
    out = @log.join("\n")
    @log = []
    print out
    nil
  end
end

$app = VirtualPeripheral.new
