#!/usr/bin/env ruby
# Offline generator for the VirtualPeripheral example's BLE blobs.
#
# WHY: the reduced PicoRuby VM on iOS lacks Array#pack / String#<< / Integer#chr,
# so BLE::GattDatabase and BLE::AdvertisingData (which build their byte blobs with
# pack/<<) cannot run on-device. So we run the REAL picoruby-ble mrblib here under
# CRuby (which has pack/<<) to produce byte-identical profile_data (BTstack ATT-DB)
# and adv_data (AD-TLV) blobs, then embed them as frozen "\xNN" literals in app.rb.
# Byte-for-byte identical to what rp2040 would compile, so the thesis (Ruby driving
# the radio via picoruby-ble) and cross-arch portability are preserved.
#
# Usage: ruby tools/gen_profile.rb   (prints Ruby literal definitions to STDOUT)

MRBLIB = File.expand_path(
  "../../../picoruby-ble-darwin-port/mrbgems/picoruby-ble/mrblib",
  __FILE__
)

# 1. Define BLE with the real constants extracted from ble.rb (the simple NAME = 0xNN
#    lines). We do NOT eval ble.rb whole — it requires mbedtls/cyw43 and defines the
#    runtime class. We only need the GATT/permission constants.
class BLE; end
ble_src = File.read(File.join(MRBLIB, "ble.rb"))
ble_src.each_line do |line|
  if line =~ /^\s+([A-Z][A-Z0-9_]*)\s*=\s*(0x[0-9a-fA-F]+|\d+)\s*$/
    BLE.const_set($1, Integer($2))
  end
end

# 2. Load the real Utils / GattDatabase / AdvertisingData. Strip `require 'pack'`
#    (CRuby's Array#pack is built in) and the GattDatabase hash path never runs here
#    (we pass no database_hash_key), so MbedTLS is never referenced.
%w[ble_utils.rb ble_gatt_database.rb ble_advertising_data.rb].each do |f|
  src = File.read(File.join(MRBLIB, f)).sub(/^require ['"]pack['"]\n/, "")
  eval(src, TOPLEVEL_BINDING, File.join(MRBLIB, f))
end

# 3. Build the fixed example profile: Heart Rate service (0x180D) with
#      0x2A37 Heart Rate Measurement  — READ | NOTIFY (+ CCCD 0x2902)
#      0x2A39 Heart Rate Control Point — WRITE
#    GAP(0x1800)/GATT(0x1801) are owned by CoreBluetooth, so we don't declare them;
#    the Darwin port skips them anyway.
db = BLE::GattDatabase.new do |d|
  d.add_service(BLE::GATT_PRIMARY_SERVICE_UUID, 0x180D) do |s|
    s.add_characteristic(BLE::READ | BLE::NOTIFY | BLE::DYNAMIC, 0x2A37,
                         BLE::READ | BLE::DYNAMIC, "\x00\x00") do |c|
      c.add_descriptor(BLE::READ | BLE::WRITE | BLE::DYNAMIC,
                       BLE::CLIENT_CHARACTERISTIC_CONFIGURATION, "\x00\x00")
    end
    s.add_characteristic(BLE::WRITE | BLE::DYNAMIC, 0x2A39,
                         BLE::WRITE | BLE::DYNAMIC, "\x00")
  end
end
profile_data = db.profile_data

# 4. Build the advertising payload: Flags (LE General Discoverable + BR/EDR not
#    supported) + complete local name "PBLE-TEST" + the 16-bit HR service UUID.
LOCAL_NAME = "PBLE-TEST"
adv_data = BLE::AdvertisingData.build do |a|
  a.add(0x01, 0x06)            # Flags
  a.add(0x03, 0x180D)          # Complete list of 16-bit Service UUIDs
  a.add(0x09, LOCAL_NAME)      # Complete local name
end

def escape(bytes)
  bytes.bytes.map { |b| format('\\x%02x', b) }.join
end

# 256-byte lookup so app.rb can turn an Integer (0..255) into a 1-byte String
# without chr/pack: BYTE_TABLE[n, 1].
byte_table = (0..255).map(&:chr).join

puts "# === GENERATED by tools/gen_profile.rb — do not edit by hand ==="
puts "# Heart Rate service 0x180D: 0x2A37 (READ|NOTIFY + CCCD), 0x2A39 (WRITE)."
puts "# Handle table (att handles assigned by GattDatabase, used below):"
db.handle_table.each do |svc_uuid, info|
  puts "#   service 0x%04X => #{info.reject { |k, _| k == :handle }.inspect} (decl handle #{info[:handle]})" rescue puts("#   #{svc_uuid.inspect} => #{info.inspect}")
end
puts
puts "PROFILE_DATA = \"#{escape(profile_data)}\".freeze   # #{profile_data.bytesize} bytes"
puts
puts "ADV_DATA = \"#{escape(adv_data)}\".freeze   # #{adv_data.bytesize} bytes"
puts
puts "BYTE_TABLE = \"#{escape(byte_table)}\".freeze   # 256 bytes: BYTE_TABLE[n,1] == n.chr"
